### ISSUE TITLE
Feature Request:  Specify Database Credentials

### ISSUE THREAD

**Issue by n00py** [mubix/solarflare#3]
Had a strange edge case where it was able to pull the database creds, but they didn't work.  Ended up finding the database in an entirely different place. 

Ended up just hard coding creds on this line and it worked.

`sqlconn.ConnectionString = "Data Source=" + sql.DbHost + ";Initial Catalog=" + sql.DbDB + ";User ID=" + sql.DbUser + ";Password=" + sql.DbPass;`

Might be nice to have the option to provide these optional values

**Comment by mubix** [comment]
Thanks for the feature request. I'll look to add that

**Comment by mubix** [comment]
Hey @n00py - adding command line arguments looks like a pain (at least to do it in a way that's clean and works well). Would having a simple config file able to be specified work? Like:
1. Run `solarflare.exe` everything is automatic
2. Run `solarflare.exe connstring.conf` and it attempts to read the connection string from the file?

**Comment by n00py** [comment]
Yes that would work I think.  I won't have any opportunity to test it as my client has come and gone, but I think it could be useful to myself or someone in the future.

**Comment by mubix** [comment]
Finally got around to this. It should now parse connection string files as the first argument. Fixed with 1e8eff943feb20d3ce25a702a5c64c3f7ec73cd1 and 12cf96430c1b286795d00546d12eb7c9351d5aca which builds correctly. I'll be testing it soon.
